stages:
  - test

test:ubuntu:
  stage: test
  tags:
    - ubuntu
  script:
    - pwd
    - whoami
    - sudo bundle install
    - bundle exec rake openstudio:style
    - bundle exec rake openstudio:dashboard
    - aws s3 cp ./test_results s3://openstudio-builds/dashboard/measures/ --recursive
